### ISSUE TITLE
Kanban Board

### ISSUE THREAD

**Issue by anderCM** [anderCM/Recipe-app#11]
There are 2 members in our Group:
- @JakariaJishan 
- @anderCM 

This is our [PROJECT](https://github.com/users/anderCM/projects/3)

**Comment by prolajumokeoni** [comment]
Hi @JakariaJishan and @anderCM, kindly update the link in your issue above to the GitHub project (Kanban board)

**Comment by anderCM** [comment]
Hello @prolajumokeoni  we have updated it, thanks

**Comment by prolajumokeoni** [comment]
Hi @Team
Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
✔️  Each card has a descriptive  title 



## Required Changes ♻️

- [ ] Kindly make sure you name your columns correctly, you should have four columns: 
- To Do
- In Progress
-  In Review
- Done

- [ ] Kindly add number of points on each cards, That number should indicate the number of points that show how complex the task is. 1 point = 1 hour of work

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Ismailco** [comment]
### Hi @JakariaJishan, @anderCM, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![cr-approve](https://user-images.githubusercontent.com/25227022/165483662-7b06c812-4cc0-40b9-a84c-4729d4cf10c3.gif)


## Highlights

✔️ Create Kanban board
✔️ All cards have a description
✔️ The tasks are divided fairly

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
